name = "SoilMulch"
uuid = "be6996d8-ce38-42dc-ae22-8b975ffb034a"
authors = ["Rodolfo Souza", "Achla Jha", "Salvatore Calabrese"]
version = "0.1.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"
DataFrames = "1.3.2"
Distributions = "0.25.46"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
